import { AppDefinition } from '../core/types';
import { FileExplorerApp } from './components/FileExplorerApp';
import { SettingsApp } from './components/SettingsApp';
import { NotesApp } from './components/NotesApp';
import { TerminalApp } from './components/TerminalApp';
import { TaskManagerApp } from './components/TaskManagerApp';
import { SystemInfoApp } from './components/SystemInfoApp';
import { CalculatorApp } from './components/CalculatorApp';
import { ClockApp } from './components/ClockApp';
import { ApiTesterApp } from './components/ApiTesterApp';
import { JsonViewerApp } from './components/JsonViewerApp';
import { DeveloperWorkspaceApp } from './components/DeveloperWorkspaceApp';
import { TextEditorApp } from './components/TextEditorApp';
import { AppCatalogApp } from './components/AppCatalogApp';
import { DiagnosticsApp } from './components/DiagnosticsApp';
import { MediaPlayerApp } from './components/MediaPlayerApp';
import { GalleryApp } from './components/GalleryApp';
import { ClipboardManagerApp } from './components/ClipboardManagerApp';
import { SnippetExpanderApp } from './components/SnippetExpanderApp';
import { QuickUtilitiesApp } from './components/QuickUtilitiesApp';
import { TasksApp } from './components/TasksApp';
import { CalendarApp } from './components/CalendarApp';
import { FocusModeApp } from './components/FocusModeApp';
import { VaultApp } from './components/VaultApp';
import { AiAssistantApp } from './components/AiAssistantApp';

export const APP_REGISTRY: Record<string, AppDefinition> = {
  'file-explorer': {
    id: 'file-explorer',
    name: 'file-explorer',
    displayName: 'File Explorer',
    description: 'Browse, manage, and organize files and folders across virtual storage.',
    version: '5.0.0',
    icon: 'Folder',
    category: 'Core',
    defaultWidth: 860,
    defaultHeight: 560,
    minWidth: 500,
    minHeight: 340,
    isPinned: true,
    component: FileExplorerApp,
  },
  'settings': {
    id: 'settings',
    name: 'settings',
    displayName: 'Settings',
    description: 'Personalize themes, sound cues, workspaces, and system preferences.',
    version: '5.0.0',
    icon: 'Settings',
    category: 'Core',
    defaultWidth: 880,
    defaultHeight: 580,
    minWidth: 600,
    minHeight: 400,
    isPinned: true,
    component: SettingsApp,
  },
  'notes': {
    id: 'notes',
    name: 'notes',
    displayName: 'Notes',
    description: 'Productivity markdown note-taking with automatic local persistence.',
    version: '5.0.0',
    icon: 'FileText',
    category: 'Productivity',
    defaultWidth: 840,
    defaultHeight: 540,
    minWidth: 480,
    minHeight: 320,
    isPinned: true,
    component: NotesApp,
  },
  'terminal': {
    id: 'terminal',
    name: 'terminal',
    displayName: 'Terminal Center',
    description: 'Interactive shell environment with built-in commands and diagnostic tools.',
    version: '5.0.0',
    icon: 'Terminal',
    category: 'Developer',
    defaultWidth: 800,
    defaultHeight: 500,
    minWidth: 480,
    minHeight: 300,
    isPinned: true,
    component: TerminalApp,
  },
  'task-manager': {
    id: 'task-manager',
    name: 'task-manager',
    displayName: 'Task Manager',
    description: 'Inspect active desktop processes, CPU & Memory usage, and end tasks.',
    version: '5.0.0',
    icon: 'Activity',
    category: 'System',
    defaultWidth: 720,
    defaultHeight: 480,
    minWidth: 460,
    minHeight: 320,
    isPinned: false,
    component: TaskManagerApp,
  },
  'system-info': {
    id: 'system-info',
    name: 'system-info',
    displayName: 'System Information',
    description: 'Hardware, operating system version, and system metrics.',
    version: '5.0.0',
    icon: 'Monitor',
    category: 'System',
    defaultWidth: 720,
    defaultHeight: 500,
    minWidth: 480,
    minHeight: 340,
    isPinned: false,
    component: SystemInfoApp,
  },
  'calculator': {
    id: 'calculator',
    name: 'calculator',
    displayName: 'Calculator',
    description: 'Perform arithmetic and scientific calculations with history tracking.',
    version: '5.0.0',
    icon: 'Calculator',
    category: 'Productivity',
    defaultWidth: 360,
    defaultHeight: 500,
    minWidth: 320,
    minHeight: 440,
    isPinned: true,
    component: CalculatorApp,
  },
  'clock': {
    id: 'clock',
    name: 'clock',
    displayName: 'Clock & Timer',
    description: 'World time zones, stopwatch with laps, and countdown timer.',
    version: '5.0.0',
    icon: 'Clock',
    category: 'Productivity',
    defaultWidth: 540,
    defaultHeight: 460,
    minWidth: 400,
    minHeight: 340,
    isPinned: false,
    component: ClockApp,
  },
  'api-tester': {
    id: 'api-tester',
    name: 'api-tester',
    displayName: 'API Tester',
    description: 'Test REST API endpoints with custom methods, headers, and payloads.',
    version: '5.0.0',
    icon: 'Send',
    category: 'Developer',
    defaultWidth: 880,
    defaultHeight: 560,
    minWidth: 560,
    minHeight: 380,
    isPinned: false,
    component: ApiTesterApp,
  },
  'json-viewer': {
    id: 'json-viewer',
    name: 'json-viewer',
    displayName: 'JSON Formatter',
    description: 'Beautify, validate, minify, and inspect JSON documents.',
    version: '5.0.0',
    icon: 'Code',
    category: 'Developer',
    defaultWidth: 700,
    defaultHeight: 480,
    minWidth: 450,
    minHeight: 320,
    isPinned: false,
    component: JsonViewerApp,
  },
  'developer-workspace': {
    id: 'developer-workspace',
    name: 'developer-workspace',
    displayName: 'Dev Workspace',
    description: 'Sprint planning, project shortcuts, launch profiles, and Git status center.',
    version: '6.0.0',
    icon: 'Code',
    category: 'Developer',
    defaultWidth: 860,
    defaultHeight: 560,
    minWidth: 540,
    minHeight: 380,
    isPinned: true,
    component: DeveloperWorkspaceApp,
  },
  'text-editor': {
    id: 'text-editor',
    name: 'text-editor',
    displayName: 'Text Editor',
    description: 'Fast lightweight code and plain text editor with tabs and line counts.',
    version: '6.0.0',
    icon: 'FileText',
    category: 'Productivity',
    defaultWidth: 760,
    defaultHeight: 520,
    minWidth: 460,
    minHeight: 320,
    isPinned: false,
    component: TextEditorApp,
  },
  'app-catalog': {
    id: 'app-catalog',
    name: 'app-catalog',
    displayName: 'App Catalog',
    description: 'Browse, launch, and manage registered applications and permissions.',
    version: '6.0.0',
    icon: 'Box',
    category: 'Core',
    defaultWidth: 840,
    defaultHeight: 540,
    minWidth: 520,
    minHeight: 360,
    isPinned: true,
    component: AppCatalogApp,
  },
  'diagnostics': {
    id: 'diagnostics',
    name: 'diagnostics',
    displayName: 'Event Viewer',
    description: 'System event logs, audit records, and JSON diagnostic telemetry export.',
    version: '6.0.0',
    icon: 'Activity',
    category: 'System',
    defaultWidth: 780,
    defaultHeight: 500,
    minWidth: 500,
    minHeight: 340,
    isPinned: false,
    component: DiagnosticsApp,
  },
  'media-player': {
    id: 'media-player',
    name: 'media-player',
    displayName: 'Groove Media Player',
    description: 'Procedural Web Audio music synthesizer and real-time spectrum visualizer.',
    version: '6.0.0',
    icon: 'Music',
    category: 'Media',
    defaultWidth: 720,
    defaultHeight: 520,
    minWidth: 480,
    minHeight: 380,
    isPinned: true,
    component: MediaPlayerApp,
  },
  'gallery': {
    id: 'gallery',
    name: 'gallery',
    displayName: 'Photo Studio',
    description: '4K wallpaper gallery, image inspector, and desktop background manager.',
    version: '6.0.0',
    icon: 'Image',
    category: 'Media',
    defaultWidth: 880,
    defaultHeight: 580,
    minWidth: 540,
    minHeight: 380,
    isPinned: true,
    component: GalleryApp,
  },
  'clipboard': {
    id: 'clipboard',
    name: 'clipboard',
    displayName: 'Clipboard History',
    description: 'Searchable clipboard history, type filters, and secure item pinning.',
    version: '8.0.0',
    icon: 'Clipboard',
    category: 'Utilities',
    defaultWidth: 780,
    defaultHeight: 520,
    minWidth: 480,
    minHeight: 340,
    isPinned: true,
    component: ClipboardManagerApp,
    permissions: ['clipboard.history.read', 'clipboard.history.write'],
  },
  'snippets': {
    id: 'snippets',
    name: 'snippets',
    displayName: 'Snippet Expander',
    description: 'Keyword expansion triggers and dynamic variable substitution sandbox.',
    version: '8.0.0',
    icon: 'Sparkles',
    category: 'Productivity',
    defaultWidth: 820,
    defaultHeight: 540,
    minWidth: 500,
    minHeight: 360,
    isPinned: false,
    component: SnippetExpanderApp,
    permissions: ['snippet.read', 'snippet.write'],
  },
  'quick-utils': {
    id: 'quick-utils',
    name: 'quick-utils',
    displayName: 'Quick Utilities',
    description: 'Color studio, UUID generator, Hash/Base64 encoders, and Regex playground.',
    version: '8.0.0',
    icon: 'Wrench',
    category: 'Utilities',
    defaultWidth: 840,
    defaultHeight: 560,
    minWidth: 540,
    minHeight: 380,
    isPinned: false,
    component: QuickUtilitiesApp,
  },
  'tasks': {
    id: 'tasks',
    name: 'tasks',
    displayName: 'Tasks & Kanban',
    description: 'Sprint Kanban boards, project tasks, priority tracking, and due dates.',
    version: '8.0.0',
    icon: 'CheckSquare',
    category: 'Productivity',
    defaultWidth: 880,
    defaultHeight: 580,
    minWidth: 560,
    minHeight: 400,
    isPinned: true,
    component: TasksApp,
    permissions: ['task.read', 'task.write'],
  },
  'calendar': {
    id: 'calendar',
    name: 'calendar',
    displayName: 'Calendar & Events',
    description: 'Monthly calendar grid, agenda scheduler, and instant meeting links.',
    version: '8.0.0',
    icon: 'Calendar',
    category: 'Productivity',
    defaultWidth: 880,
    defaultHeight: 580,
    minWidth: 540,
    minHeight: 380,
    isPinned: true,
    component: CalendarApp,
    permissions: ['calendar.read', 'calendar.write'],
  },
  'focus': {
    id: 'focus',
    name: 'focus',
    displayName: 'Focus Mode',
    description: 'Pomodoro countdown, deep work sessions, and ambient audio synthesizer.',
    version: '8.0.0',
    icon: 'Flame',
    category: 'Productivity',
    defaultWidth: 680,
    defaultHeight: 540,
    minWidth: 460,
    minHeight: 380,
    isPinned: false,
    component: FocusModeApp,
  },
  'vault': {
    id: 'vault',
    name: 'vault',
    displayName: 'Security Vault',
    description: 'Encrypted password vault, TOTP 2FA tokens, and strong key generator.',
    version: '8.0.0',
    icon: 'ShieldCheck',
    category: 'System',
    defaultWidth: 820,
    defaultHeight: 560,
    minWidth: 520,
    minHeight: 380,
    isPinned: true,
    component: VaultApp,
    permissions: ['vault.read', 'vault.write'],
  },
  'ai-assistant': {
    id: 'ai-assistant',
    name: 'ai-assistant',
    displayName: 'Antigravity AI',
    description: 'On-device desktop AI assistant for SQL queries, React help, and workflow commands.',
    version: '8.0.0',
    icon: 'Bot',
    category: 'Productivity',
    defaultWidth: 840,
    defaultHeight: 580,
    minWidth: 500,
    minHeight: 400,
    isPinned: true,
    component: AiAssistantApp,
    permissions: ['ai.prompt', 'ai.model.switch'],
  },
};

export const getAllApps = (): AppDefinition[] => Object.values(APP_REGISTRY);

export const getPinnedApps = (): AppDefinition[] =>
  Object.values(APP_REGISTRY).filter((app) => app.isPinned);

export const getAppById = (id: string): AppDefinition | undefined => APP_REGISTRY[id];
