import { AppDefinition } from '../core/types';
import { FileExplorerApp } from './components/FileExplorerApp';
import { SettingsApp } from './components/SettingsApp';
import { NotesApp } from './components/NotesApp';
import { TerminalApp } from './components/TerminalApp';
import { TaskManagerApp } from './components/TaskManagerApp';
import { SystemInfoApp } from './components/SystemInfoApp';
import { CalculatorApp } from './components/CalculatorApp';
import { ClockApp } from './components/ClockApp';
import { ApiTesterApp } from './components/ApiTesterApp';
import { JsonViewerApp } from './components/JsonViewerApp';

export const APP_REGISTRY: Record<string, AppDefinition> = {
  'file-explorer': {
    id: 'file-explorer',
    name: 'file-explorer',
    displayName: 'File Explorer',
    description: 'Browse, manage, and organize files and folders across virtual storage.',
    version: '5.0.0',
    icon: 'Folder',
    category: 'Core',
    defaultWidth: 860,
    defaultHeight: 560,
    minWidth: 500,
    minHeight: 340,
    isPinned: true,
    component: FileExplorerApp,
  },
  'settings': {
    id: 'settings',
    name: 'settings',
    displayName: 'Settings',
    description: 'Personalize themes, sound cues, workspaces, and system preferences.',
    version: '5.0.0',
    icon: 'Settings',
    category: 'Core',
    defaultWidth: 880,
    defaultHeight: 580,
    minWidth: 600,
    minHeight: 400,
    isPinned: true,
    component: SettingsApp,
  },
  'notes': {
    id: 'notes',
    name: 'notes',
    displayName: 'Notes',
    description: 'Productivity markdown note-taking with automatic local persistence.',
    version: '5.0.0',
    icon: 'FileText',
    category: 'Productivity',
    defaultWidth: 840,
    defaultHeight: 540,
    minWidth: 480,
    minHeight: 320,
    isPinned: true,
    component: NotesApp,
  },
  'terminal': {
    id: 'terminal',
    name: 'terminal',
    displayName: 'Terminal Center',
    description: 'Interactive shell environment with built-in commands and diagnostic tools.',
    version: '5.0.0',
    icon: 'Terminal',
    category: 'Developer',
    defaultWidth: 800,
    defaultHeight: 500,
    minWidth: 480,
    minHeight: 300,
    isPinned: true,
    component: TerminalApp,
  },
  'task-manager': {
    id: 'task-manager',
    name: 'task-manager',
    displayName: 'Task Manager',
    description: 'Inspect active desktop processes, CPU & Memory usage, and end tasks.',
    version: '5.0.0',
    icon: 'Activity',
    category: 'System',
    defaultWidth: 720,
    defaultHeight: 480,
    minWidth: 460,
    minHeight: 320,
    isPinned: false,
    component: TaskManagerApp,
  },
  'system-info': {
    id: 'system-info',
    name: 'system-info',
    displayName: 'System Information',
    description: 'Hardware, operating system version, and system metrics.',
    version: '5.0.0',
    icon: 'Monitor',
    category: 'System',
    defaultWidth: 720,
    defaultHeight: 500,
    minWidth: 480,
    minHeight: 340,
    isPinned: false,
    component: SystemInfoApp,
  },
  'calculator': {
    id: 'calculator',
    name: 'calculator',
    displayName: 'Calculator',
    description: 'Perform arithmetic and scientific calculations with history tracking.',
    version: '5.0.0',
    icon: 'Calculator',
    category: 'Productivity',
    defaultWidth: 360,
    defaultHeight: 500,
    minWidth: 320,
    minHeight: 440,
    isPinned: true,
    component: CalculatorApp,
  },
  'clock': {
    id: 'clock',
    name: 'clock',
    displayName: 'Clock & Timer',
    description: 'World time zones, stopwatch with laps, and countdown timer.',
    version: '5.0.0',
    icon: 'Clock',
    category: 'Productivity',
    defaultWidth: 540,
    defaultHeight: 460,
    minWidth: 400,
    minHeight: 340,
    isPinned: false,
    component: ClockApp,
  },
  'api-tester': {
    id: 'api-tester',
    name: 'api-tester',
    displayName: 'API Tester',
    description: 'Test REST API endpoints with custom methods, headers, and payloads.',
    version: '5.0.0',
    icon: 'Send',
    category: 'Developer',
    defaultWidth: 880,
    defaultHeight: 560,
    minWidth: 560,
    minHeight: 380,
    isPinned: false,
    component: ApiTesterApp,
  },
  'json-viewer': {
    id: 'json-viewer',
    name: 'json-viewer',
    displayName: 'JSON Formatter',
    description: 'Beautify, validate, minify, and inspect JSON documents.',
    version: '5.0.0',
    icon: 'Code',
    category: 'Developer',
    defaultWidth: 700,
    defaultHeight: 480,
    minWidth: 450,
    minHeight: 320,
    isPinned: false,
    component: JsonViewerApp,
  },
};

export const getAllApps = (): AppDefinition[] => Object.values(APP_REGISTRY);

export const getPinnedApps = (): AppDefinition[] =>
  Object.values(APP_REGISTRY).filter((app) => app.isPinned);

export const getAppById = (id: string): AppDefinition | undefined => APP_REGISTRY[id];
